notifications:
  email: false
# begin chunk for https://github.com/joerick/cibuildwheel windows/mac deployment

language: python
python:
  - 3.8

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = windows ]]; then
        choco install python --version 3.8.0
        export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        ln -s /c/Python38/python.exe /c/Python38/python3.exe
    fi

script:
  - python3 setup.py install
  - pytest
# end chunk for https://github.com/joerick/cibuildwheel windows/mac deployment

stages:
  - test
  - deploy


matrix:
  include:
    - sudo: required
      language: python
      python:
        - "3.6"
      env:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
      # command to install dependencies
      install:
        - pip install pipenv
        - pipenv install --dev --skip-lock
        - pipenv run python setup.py build_ext --inplace
        - pipenv install -e . --skip-lock
      # command to run tests
      script:
        - pipenv run pytest filediffs/filediffs_python/tests/test_filediffs.py --doctest-cython -v
    - sudo: required
      language: python
      python:
        - "3.7"
      env:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
      # command to install dependencies
      install:
        - pip install pipenv
        - pipenv install --dev --skip-lock
        - pipenv run python setup.py build_ext --inplace
        - pipenv install -e . --skip-lock
      # command to run tests
      script:
        - pipenv run pytest filediffs/filediffs_python/tests/test_filediffs.py --doctest-cython -v
    - sudo: required
      language: python
      python:
        - "3.8"
      env:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
      # command to install dependencies
      install:
        - pip install pipenv
        - pipenv install --dev --skip-lock
        - pipenv run python setup.py build_ext --inplace
        - pipenv install -e . --skip-lock
      # command to run tests
      script:
        - pipenv run pytest filediffs/filediffs_python/tests/test_filediffs.py --doctest-cython -v
    - sudo: required
      # build wheels using manylinux
      stage: deploy
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
        PLAT=manylinux1_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
        - ls wheelhouse/
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        PLAT=manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -e PLAT=$PLAT -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
        - ls wheelhouse/
    # begin chunk for https://github.com/joerick/cibuildwheel windows / mac deployment
    # Deploy on windows
    - stage: deploy
      name: Build and deploy Windows wheels
      os: windows
      language: shell
      install: python3 -m pip install cibuildwheel==1.5.5
      script: python3 -m cibuildwheel --output-dir wheelhouse
      after_success: |
        # have a look at the wheelhouse.
        ls wheelhouse/
        python3 -m pip install twine
        python3 -m twine upload --skip-existing wheelhouse/*.whl
    # Deploy on mac
    - stage: deploy
      name: Build and deploy macOS wheels
      os: osx
      language: shell
      install: python3 -m pip install cibuildwheel==1.5.5
      script: python3 -m cibuildwheel --output-dir wheelhouse
      after_success: |
        python3 -m pip install twine
        python3 -m twine upload --skip-existing wheelhouse/*.whl



env:
  global:
    - TWINE_USERNAME=__token__
    # Skip Python 2.7 and Python 3.5
    - CIBW_SKIP=cp27-*
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings