# This is a basic workflow to help you get started with Actions

name: publish_to_pypi

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ depl ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        python_version: '3.7.1'
        poetry_version: '==1.0.5'
        pypi_token: ${{ secrets.PYPI_TOKEN }}
